Lmod has detected the following error: The following module(s) are unknown:
"cuda/12.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "cuda/12.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



cuda available with GPU: Tesla V100-SXM2-16GB
[I] Loading dataset OGBG-MOLTOX21...
[I] Finished loading.
[I] Data load time: 6.3714s
MODEL DETAILS:

MODEL/Total parameters: SAN 1051081
[!] -LSPE: Initializing graph positional encoding with rand walk features.
[!] Time taken:  25.271052837371826
[!] -LSPE (For viz later): Adding lapeigvecs to key 'eigvec' for every graph.
[!] Time taken:  2.86102294921875e-06
[!] Adding full graph connectivity..
Time taken to add full graph connectivity:  161.17732334136963
Training Graphs:  6015
Validation Graphs:  782
Test Graphs:  782
  0%|          | 0/1000 [00:00<?, ?it/s]Epoch 0:   0%|          | 0/1000 [00:00<?, ?it/s]Epoch 0:   0%|          | 0/1000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 509, in <module>
    main()
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 504, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 197, in train_val_pipeline
    epoch_train_loss, epoch_train_acc, optimizer = train_epoch(model, optimizer, device, train_loader, epoch, evaluator)
  File "/home/mikemont/final_project/gnn-lspe/train/train_OGBMOL_graph_classification.py", line 42, in train_epoch_sparse
    batch_pred, __ = model.forward(batch_graphs, batch_x, batch_pos_enc, batch_e, batch_snorm_n)
  File "/home/mikemont/final_project/gnn-lspe/nets/OGBMOL_graph_classification/san_net.py", line 93, in forward
    h, p = conv(g, h, p, e, snorm_n)
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mikemont/final_project/gnn-lspe/layers/san_gt_lspe_layer.py", line 250, in forward
    h_attn_out = self.attention_h(g, h, p, e)
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mikemont/final_project/gnn-lspe/layers/san_gt_lspe_layer.py", line 195, in forward
    self.propagate_attention(g)
  File "/home/mikemont/final_project/gnn-lspe/layers/san_gt_lspe_layer.py", line 159, in propagate_attention
    g.send_and_recv(eids, fn.src_mul_edge('V_h', 'score_soft', 'V_h'), fn.sum('V_h', 'wV'))
AttributeError: module 'dgl.function' has no attribute 'src_mul_edge'
